# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('booking_date', models.DateField()),
                ('booking_time', models.IntegerField(choices=[(9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('booking_date', 'booking_time')]),
        ),
    ]
