# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_slot',
            field=models.CharField(choices=[(9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], max_length=30),
        ),
    ]
